---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: kube-apiserver

spec:
  endpoints:
    - port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes
        insecureSkipVerify: false

  namespaceSelector:
    matchNames:
      - default

  selector:
    matchLabels:
      provider: kubernetes
      component: apiserver

...
