---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: kube-dns

spec:
  endpoints:
    - port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  namespaceSelector:
    matchNames:
      - kube-system

  selector:
    matchLabels:
      k8s-app: kube-dns

...
