---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: kube-etcd

spec:
  endpoints:
    - port: client
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token

  namespaceSelector:
    matchNames:
      - kube-system

  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes
      app.kubernetes.io/component: etcd

...
