---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: prometheus-server

rules:
  - apiGroups:
      - ""
    resources:
      - "services"
      - "endpoints"
      - "pods"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "extensions"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - "ingresses"
    verbs:
      - "get"
      - "list"
      - "watch"
  - apiGroups:
      - ""
    resources:
      - "nodes/metrics"
    verbs:
      - "get"
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - "get"

...
