---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus

metadata:
  name: server

spec:
  version: v2.27.0
  replicas: 1
  serviceAccountName: prometheus-server

  retention: 2w
  enableAdminAPI: true
  portName: http
  retentionSize: 45GB

  resources:
    limits:
      cpu: 2000m
      memory: 2500Mi
    requests:
      cpu: 1000m
      memory: 2500Mi

  storage:
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi

  podMetadata:
    labels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: server

  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000

  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  probeNamespaceSelector: {}
  probeSelector: {}

  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}

  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      prometheus: server
      role: rules

...
