---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: prometheus-server

spec:
  endpoints:
    - port: http
      scheme: http
      interval: 30s

  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/component: server

...
