---
apiVersion: v1
kind: Service

metadata:
  name: weave-net
  labels:
    app.kubernetes.io/name: weave
    app.kubernetes.io/part-of: prometheus

spec:
  clusterIP: None

  selector:
    name: weave-net

  ports:
    - name: metrics
      port: 6782

...
